name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main # Your main branch
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Use a recent LTS version

      - name: Install dependencies
        run: npm ci

      - name: Build static site
        run: npm run build

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out # Next.js exports to the 'out' directory

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
